# Generated by Django 3.1.3 on 2020-11-23 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Product',
        ),
    ]
