# Generated by Django 3.1.3 on 2020-11-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_auto_20201123_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, choices=[('kilograms', 'kgs'), ('grams', 'grams')], max_length=30, null=True),
        ),
    ]
