# Generated by Django 3.1.3 on 2020-11-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, choices=[('kilograms', 'kg'), ('grams', 'g'), ('pounds', 'lbs')], max_length=30, null=True),
        ),
    ]
