# Generated by Django 3.1.3 on 2020-11-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0005_auto_20201123_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, choices=[('kg', 'kg'), ('g', 'g'), ('lbs', 'lbs'), ('liters', 'liters')], max_length=30, null=True),
        ),
    ]
