# Generated by Django 3.1.3 on 2020-11-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0009_auto_20201124_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='notes',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
    ]
